---
title: The Enchanted Tiki Shed
timezone: UTC
collections:
  cocktails:
    title: Cocktails
    output: true
    permalink: "/cocktail/:title"
    layout: cocktail
  posts:
    title: News
    output: true
    layout: post
  uploads:
    title: Uploads
    output: true
author: Jungle Skipper
description: 
url: https://enchantedtikished.com
twitter:
  username: _jungleskippr
social:
  name: Jungle Skipper
  links:
  - https://twitter.com/_jungleskippr
  - https://www.facebook.com/thejungleskipper
  - https://instagram.com/_jungleskippr
lang: en_UK
baseurl: ''
paginate: 10
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jemoji
permalink: "/:categories/:title"
sass:
  sass_dir: _sass
emptyArray: []
